config/routes.rb
Rails.application.routes.draw do
  resources :projects
  resources :task_times do
    member do
      get :continue_task
    end
  end
  get 'oauth_callbacks/twitter'
  devise_for :users, :controllers => { :omniauth_callbacks => "oauth_callbacks" }
  root 'task_times#index'
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
end

app/models/task_time.rb
class TaskTime < ActiveRecord::Base
  belongs_to :project
  before_save :today

  def time
    diff = self.end_time.to_time - self.init_time.to_time
    '%d:%02d:%02d' % [ diff / 3600, (diff / 60) % 60, diff % 60 ]
  end

  def today
    self.task_date = DateTime.now if self.task_date.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
   devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :omniauthable, :omniauth_providers => [:twitter]

  has_attached_file :avatar,
   styles: { medium: "256x256>", profile: "128x128>", small: "64x64", icon: "64x64" }, default_url: ":user_placehold_it"

  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

   def self.oauth(auth)
     where(provider: auth.provider, user_id: auth.uid).first_or_create do |user|
       user.provider = auth.provider #social network provider default: Twitter
       user.user_id = auth.uid
       user.name = auth.info.name
       user.avatar_from_url auth.info.image
       user.email = auth.info.email
       user.password = Devise.friendly_token[0,20]
     end
   end

   def avatar_from_url url
     self.avatar = open(url)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/oauth_callbacks_controller.rb
class OauthCallbacksController < Devise::OmniauthCallbacksController
  def twitter
    @user = User.oauth(request.env["omniauth.auth"])
    sign_in_and_redirect @user
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'admin'
  before_action :load_project, only: [:edit, :destroy, :update]


  def index
    @projects = Project.all.page(params[:page]).per(20)
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      flash[:success] = "Project Created successfully"
    else
      flash[:success] = "Errors creating project: #{@project.errors.messages.to_sentence}"
    end
    redirect_to action: :index
  end

  def edit
  end

  def update
    if @project.update_attributes(project_params)
      flash[:success] = "Project Updated successfully"
    else
      flash[:success] = "Errors Updating project: #{@project.errors.messages.to_sentence}"
    end
    redirect_to action: :index
  end

  def destroy
    if @project.delete
      flash[:success] = "Project Deleted successfully"
    else
      flash[:success] = "Errors Deleting project: #{@project.errors.messages.to_sentence}"
    end
    redirect_to action: :index
  end

  private
    def load_project
      @project = Project.find_by(id: params[:id])
    end

    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/task_times_controller.rb
class TaskTimesController < ApplicationController
  layout 'admin'
  before_action :load_task_time, only: [:edit, :destroy, :update, :continue_task]
  before_action :load_projects, only: [:index,:edit, :new]


  def index
    @q = TaskTime.ransack(params[:q])
    @task_times = @q.result.includes(:project).order("created_at DESC").page(params[:page])
  end

  def new
    @task_time = TaskTime.new
  end

  def create
    @task_time = TaskTime.new(task_time_params)
    if @task_time.save
      flash[:success] = "Time Created successfully"
    else
      flash[:error] = "Errors creating task_time: #{@task_time.errors.messages.to_sentence}"
    end
    respond_to do |format|
      format.js {  }
      format.html {

        redirect_to action: :index
      }
    end
  end

  def edit
  end

  def update
    if @task_time.update_attributes(task_time_params)
      flash[:success] = "Time Updated successfully"
    else
      flash[:success] = "Errors Updating time: #{@task_time.errors.messages.to_sentence}"
    end
    redirect_to action: :index
  end

  def destroy
    if @task_time.delete
      flash[:success] = "Time Deleted successfully"
    else
      flash[:success] = "Errors Deleting time: #{@task_time.errors.messages.to_sentence}"
    end
    redirect_to action: :index
  end

  def continue_task
    respond_to do |format|
      format.js {  }
    end
  end

  private
    def load_task_time
      @task_time = TaskTime.find_by(id: params[:id])
    end

    def task_time_params
      params.require(:task_time).permit(:name, :init_time, :end_time, :project_id)
    end

    def load_projects
      @projects = Project.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BOOTSTRAP_FLASH_MSG = {
    success: 'alert-success',
    error:   'alert-danger',
    alert:   'alert-warning',
    notice:  'alert-info'
  }

  def alert_class_for(flash_type)
    BOOTSTRAP_FLASH_MSG.fetch(flash_type.to_sym, flash_type.to_s)
  end

  def active_menu(action)
    "active" if params[:controller].include? action
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/task_times_helper.rb
module TaskTimesHelper
end

app/views/layouts/admin.html.slim
doctype html
html
  head
    = render partial: "shared/header"

  body.hold-transition.skin-red.sidebar-mini
    .wrapper
      = render partial: "shared/user_navbar"
      = render partial: "shared/admin_sidebar"

      .content-wrapper
        section.content-header
          .row
            = render "shared/flash_messages", flash: flash
          = yield :head

        section.content
          = yield
      = render partial: "shared/admin_footer"
      = render partial: "shared/admin_asidebar"

app/views/layouts/application.html.slim
doctype html
html
  head
    = render partial: "shared/header"

  body.hold-transition.login-page
    section.content-header
      .row
        .col-md-4.col-md-offset-4
          = render "shared/flash_lg_messages", flash: flash
    = yield

app/views/oauth_callbacks/twitter.html.slim
h1 OauthCallbacks#twitter
p Find me in app/views/oauth_callbacks/twitter.html.slim

app/views/projects/_form.html.slim
.row
  .col-md-6
    .box.box-default
      .box-body
        = simple_form_for @project do |f|
          = f.error_notification
          .form-inputs
            = f.input :name, required: true, autofocus: true

          .form-actions
            = f.button :submit, "Save"

app/views/projects/_project.html.slim
tr
  td = project.name

  td
    = link_to "Edit", edit_project_path(project), class: 'btn btn-info btn-xs'
    = link_to  "Delete", project, method: :delete, data: { confirm: "Are you sure to delete this record?" }, class: 'btn btn-danger btn-xs'

app/views/projects/edit.html.slim
= content_for :head do
    h1 Edit Project
= render partial: "form"

app/views/projects/index.html.slim
= content_for :head do
    h1
      | Projects Management
.row
  .col-md-6
    .box
      .box-header
        h3.box-title Projects
        .box-tools
          .input-group
            = link_to "Create new Project", new_project_path, class: "btn btn-primary btn-xs pull-right"

      .box-body
        table.table.table-condesed
          thead
            tr
              th Name
              th Actions
          tbody
            = render(@projects) || raw("<tr><td class='text-muted text-center no-records-text' colspan='5'>No Projects</td></tr>")
      .box-footer
        .text-center
          = paginate @projects

app/views/projects/new.html.slim
= content_for :head do
    h1 New Project
= render partial: "form"

app/views/shared/_admin_asidebar.html.slim
aside.control-sidebar.control-sidebar-dark
  .tab-content
    #control-sidebar-settings-tab.tab-pane.active
      h3.control-sidebar-heading Opciones Generales
      ul.control-sidebar-menu
        li
          = link_to "#" do
            i.menu-icon.fa.fa-user.bg-blue
            .menu-info
              h4.control-sidebar-subheading Asignar Usuarios
              p Otorga a usuarios permisos de actualizar temas.

.control-sidebar-bg

app/views/shared/_admin_footer.html.slim
footer.main-footer
  /! To the right
  .pull-right.hidden-xs
    | Time tracker
  /! Default to the left
  strong
    | Copyright &copy; 2016
    a href="#"  Ricardo Montes Test.
  | All rights reserved.

app/views/shared/_admin_sidebar.html.slim
aside.main-sidebar
  section.sidebar
    .user-panel
      .pull-left.image
        = image_tag current_user.avatar.url(:profile), class:"img-circle", alt: ("User picture")
      .pull-left.info
        p
          = current_user.name

        a href="#"
          i.fa.fa-circle.text-success
          | Online

    ul.sidebar-menu
      li.header Menu

      li class="#{active_menu('projects')}"
        =link_to projects_path do
          i.fa.fa-bars
          span Projects
      li class="#{active_menu('task_times')}"
        =link_to task_times_path do
          i.fa.fa-bars
          span Times

app/views/shared/_flash_lg_messages.html.slim
- flash.each do |type, message|
  #flash_messages class=("alert #{alert_class_for(type)} alert-dismissible fade in")
    button.close data-dismiss="alert" type="button" aria-hidden="true"
      | ×
    = message

app/views/shared/_flash_messages.html.slim
- flash.each do |type, message|
  .col-md-4
    #flash_messages class=("alert #{alert_class_for(type)} alert-dismissible fade in")
      button.close data-dismiss="alert" type="button" aria-hidden="true"
        | ×
      = message

app/views/shared/_header.html.slim
title Time Tracker
meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport" /
= stylesheet_link_tag    'application', media: 'all'
= javascript_include_tag 'application'

link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet" /
link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet" /

= csrf_meta_tags

app/views/shared/_user_navbar.html.slim
header.main-header
  = link_to root_path, class: "logo" do
    span.logo-mini
      b TT
    span.logo-lg
      b TIME TRACKER
  nav.navbar.navbar-static-top role="navigation"
    a.sidebar-toggle data-toggle="offcanvas" href="#" role="button"
      span.sr-only Toggle navigation
    .navbar-custom-menu
      ul.nav.navbar-nav
        = render partial: "shared/userdata_info"

app/views/shared/_user_options.html.slim
/! Messages: style can be found in dropdown.less
li.dropdown.messages-menu
  /! Menu toggle button
  a.dropdown-toggle data-toggle="dropdown" href="#"
    i.fa.fa-envelope-o
    span.label.label-success 4
  ul.dropdown-menu
    li.header You have 4 messages
    li
      /! inner menu: contains the messages
      ul.menu
        li
          /! start message
          a href="#"
            .pull-left
              /! User Image
              img.img-circle alt=("User Image") src="http://placehold.it/160x160" /
              /! Message title and timestamp
            h4
              | Support Team
              small
                i.fa.fa-clock-o
                | 5 mins
            /! The message
            p Why not buy a new awesome theme?
        /! end message
      /! /.menu
    li.footer
      a href="#"  See All Messages
/! /.messages-menu
/! Notifications Menu
li.dropdown.notifications-menu
  /! Menu toggle button
  a.dropdown-toggle data-toggle="dropdown" href="#"
    i.fa.fa-bell-o
    span.label.label-warning 10
  ul.dropdown-menu
    li.header You have 10 notifications
    li
      /! Inner Menu: contains the notifications
      ul.menu
        li
          /! start notification
          a href="#"
            i.fa.fa-users.text-aqua
            | 5 new members joined today
        /! end notification
    li.footer
      a href="#"  View all
/! Tasks Menu
li.dropdown.tasks-menu
  /! Menu Toggle Button
  a.dropdown-toggle data-toggle="dropdown" href="#"
    i.fa.fa-flag-o
    span.label.label-danger 9
  ul.dropdown-menu
    li.header You have 9 tasks
    li
      /! Inner menu: contains the tasks
      ul.menu
        li
          /! Task item
          a href="#"
            /! Task title and progress text
            h3
              | Design some buttons
              small.pull-right 20%
            /! The progress bar
            .progress.xs
              /! Change the css width attribute to simulate progress
              .progress-bar.progress-bar-aqua aria-valuemax="100" aria-valuemin="0" aria-valuenow="20" role="progressbar" style=("width: 20%")
                span.sr-only 20% Complete
        /! end task item
    li.footer
      a href="#"  View all tasks
/! User Account Menu

app/views/shared/_userdata_info.html.slim
li.dropdown.user.user-menu
  /! Menu Toggle Button
  a.dropdown-toggle data-toggle="dropdown" href="#"
    /! The user image in the navbar
    = image_tag current_user.avatar.url(:profile), class:"user-image", alt: ("User picture")
    /! hidden-xs hides the username on small devices so only the image appears.
    span.hidden-xs = current_user.name
  ul.dropdown-menu
    /! The user image in the menu
    li.user-header
      = image_tag current_user.avatar.url(:profile), class:"img-circle", alt: ("User picture")
      p
        = current_user.name

        small
          | Member Since
          = " #{I18n.l current_user.created_at, format: :long}"
    /! Menu Body
    /! Menu Footer
    li.user-footer
      .pull-left
        /= link_to "Pérfil", "#", class: "btn btn-default btn-flat"

      .pull-right
        = link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-default btn-flat"

app/views/task_times/_form.html.slim
.row
  .col-md-6
    .box.box-default
      .box-body
        = simple_form_for @task_time do |f|
          = f.error_notification
          .form-inputs
            = f.input :name, autofocus: true
            = f.input :init_time, as: :time, required: true
            = f.input :end_time, as: :time, required: true
            = f.input :task_date, as: :date, required: true
            = f.input :project_id, as: :select, :collection => @projects

          .form-actions
            = f.button :submit, "Save"

app/views/task_times/_task_time.html.slim
tr
  td = task_time.name.present? ? task_time.name : "(No Description)"
  td = task_time.project.present? ? task_time.project.name : "(No Project)"
  td = task_time.time
  td = "#{task_time.init_time.localtime.strftime('%I:%M:%S %p')} - #{task_time.end_time.localtime.strftime('%I:%M:%S %p')}"
  td = task_time.task_date.strftime('%D')

  td
    = link_to raw("<i class='fa fa-play'></i> Continue"), continue_task_task_time_path(task_time), :remote => true, class: 'btn btn-success btn-xs'
    = link_to raw("<i class='fa fa-pencil'></i> Edit"), edit_task_time_path(task_time), class: 'btn btn-info btn-xs'
    = link_to raw("<i class='fa fa-trash'></i> Delete"), task_time, method: :delete, data: { confirm: "Are you sure to delete this record?" }, class: 'btn btn-danger btn-xs'

app/views/task_times/continue_task.js.erb
$("#name").val("<%=escape_javascript @task_time.name%>")
$("#project_id").val("<%=escape_javascript @task_time.project_id.to_s%>")

$("#toggleTimer").click()
console.log("<%=escape_javascript @task_time.name%>")

app/views/task_times/create.js.erb
$(".task-times").prepend("<%= escape_javascript render(partial: 'task_time', locals: {task_time: @task_time})%>");

app/views/task_times/edit.html.slim
= content_for :head do
    h1 Edit Time
= render partial: "form"

app/views/task_times/index.html.slim
= content_for :head do
    h1
      | Time registry
      small List of times

.row
  .col-md-12
    .box.box-success
      .box-body
        .row
          .col-xs-3
            = text_field_tag :name, nil, class: 'form-control', placeholder: 'Enter task name'
          .col-xs-4
            = select_tag :project_id, options_from_collection_for_select(@projects, "id", "name"), {class:'form-control', prompt: 'Select project...'}
          .col-xs-2.text-center
            span id='timeCount' style="font-size:24px"
              |00:00
          .col-xs-3.text-right
            button.btn.btn-primary.btn-block id="toggleTimer" aria-pressed="false" autocomplete="off" data-toggle="button" type="button" onclick="toggleTimer(this)" Start
      /! /.box-body
    .box.box-primary
      .box-header.with-border
        h3.box-title = "Recently registered"
        .box-tools.pull-right
          .input-group
            = link_to "Create Manually", new_task_time_path, class: "btn btn-primary btn-xs pull-right"
      /! /.box-header
      .box-body
        table.table.table-condesed
          thead
            tr
              th = sort_link(@q, :name, 'Task Name', default_order: :desc)
              th = sort_link(@q, :project_id, 'Project', default_order: :desc)
              th Time
              th
              th = sort_link(@q, :task_date, 'Task date', default_order: :desc)
              th Actions
          tbody.task-times
            = render partial: "task_time", collection: @task_times, as: :task_time

app/views/task_times/new.html.slim
= content_for :head do
    h1 New Time
= render partial: "form"